server:
  port: 8082

spring:
  application:
    name: stayease-property-service

  datasource:
    url: ${PROPERTY_DB_URL}
    username: ${PROPERTY_DB_USERNAME}
    password: ${PROPERTY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true