server:
  port: 8082

spring:
  application:
    name: stayease-property-service

  datasource:
    url: jdbc:postgresql://localhost:5432/stayease_property_db
    username: postgres
    password: Password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true